
# THE GAME VARIANT FIXES THE PARAMETERS BELOW
# CHANGE ONLY FOR TRAINING OR EXPERIMENTATION
NUM_ROUNDS = 1000
STARTING_STACK = 400
BIG_BLIND = 2
SMALL_BLIND = 1

# Hyperparameters for Bounty Holdem
ROUNDS_PER_BOUNTY = 25  # unlikely to change
BOUNTY_RATIO = 1.5  # subject to change, ratio as a multiplier of pot
BOUNTY_CONSTANT = 10

PLAYER_TIMEOUT = 120
